import { NextPage } from 'next'
import Router from 'next/router'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react'

import useSession from '../hooks/useSession'

const Home: NextPage = () => {

  const { isLogged } = useSession()

  useEffect(() => {
    if(isLogged){
        Router.push('/dashboard');
    }
  }, [isLogged])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Landing Page</h1>
      <Link href='/signup'>Sign up</Link>
      <Link href='/signin'>Sign in</Link>
    </div>
  )
}

export default Home
